In [ ]:
%matplotlib inline
import numpy
from matplotlib import pyplot
from matplotlib import animation
from JSAnimation.IPython_display import display_animation

In [14]:
import numpy
nx = 81
x = numpy.linspace(0,4,nx)
x

array([ 0.  ,  0.05,  0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,
        0.45,  0.5 ,  0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,
        0.9 ,  0.95,  1.  ,  1.05,  1.1 ,  1.15,  1.2 ,  1.25,  1.3 ,
        1.35,  1.4 ,  1.45,  1.5 ,  1.55,  1.6 ,  1.65,  1.7 ,  1.75,
        1.8 ,  1.85,  1.9 ,  1.95,  2.  ,  2.05,  2.1 ,  2.15,  2.2 ,
        2.25,  2.3 ,  2.35,  2.4 ,  2.45,  2.5 ,  2.55,  2.6 ,  2.65,
        2.7 ,  2.75,  2.8 ,  2.85,  2.9 ,  2.95,  3.  ,  3.05,  3.1 ,
        3.15,  3.2 ,  3.25,  3.3 ,  3.35,  3.4 ,  3.45,  3.5 ,  3.55,
        3.6 ,  3.65,  3.7 ,  3.75,  3.8 ,  3.85,  3.9 ,  3.95,  4.  ])

In [15]:
u = numpy.zeros(nx)
u

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.])

In [16]:
u[:int(nx/2)] = 1
u

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.])

In [18]:
index, = numpy.where(x == 2)
index = index[0]
index

40

In [20]:
print(x[index-1])
print(x[index])
print(x[index+1])
print(u[index-1])
print(u[index])
print(u[index+1])

1.95
2.0
2.05
1.0
0.0
0.0


In [ ]:
def u_initial(nx):
    u = numpy.zeros(nx)
    u[:int(nx/2)] = 1
    return u

In [ ]:
def computeF(u):
    """Computes flux F
    
    Parameters
    ----------
    u : array of floats
    
    Returns
    -------
    F : array of floats
        Array with flux at every point x
    """
    
    return (1/2)*u**2

In [ ]:
def maccormack(u, nt, dt, dx):
    """Computes the solution with MacCormack scheme
    
    Parameters
    ----------
    u : array of floats
    nt : int
         Number of time steps
    dt : float
         Time-step size
    dx : float
         Mesh spacing
    
    Returns
    -------
    un : array of floats
    """
    
    un = numpy.zeros((nt,len(u)))
    u_star = numpy.empty_like(u)
    un[:,:] = u.copy()
    u_star = u.copy()
    
    for t in range(1,nt):
        F = computeF(u)
        u_star[:-1] = u[:-1] - dt/dx * (F[1:]-F[:-1])
        Fstar = computeF(u_star)
        un[t,1:] = .5 * (u[1:]+u_star[1:] - dt/dx * (Fstar[1:] - Fstar[:-1]))
        u = un[t].copy()
    
    return un

In [ ]:
nx = 81
nt = 70
dx = 4.0/(nx-1)

def animate(data):
    x = numpy.linspace(0,4,nx)
    y = data
    line.set_data(x,y)
    return line,

u = u_initial(nx)
sigma = .5
dt = sigma*dx

un = maccormack(u,nt,dt,dx)

fig = pyplot.figure();
ax = pyplot.axes(xlim=(0,4),ylim=(-.5,2));
line, = ax.plot([],[],lw=2);

anim = animation.FuncAnimation(fig, animate, frames=un, interval=50)
display_animation(anim, default_mode='once')