In [1]:
%matplotlib inline
import numpy
from matplotlib import pyplot
from matplotlib import rcParams
rcParams['font.family'] = 'serif'
rcParams['font.size'] = 16
from matplotlib import animation
from IPython.display import HTML

In [2]:
# initial conditions
nx = 81
dx = .25
dt = 0.0002
gamma = 1.4

In [3]:
x = numpy.linspace(-10,10,nx)
print(len(x))
x

81


array([-10.  ,  -9.75,  -9.5 ,  -9.25,  -9.  ,  -8.75,  -8.5 ,  -8.25,
        -8.  ,  -7.75,  -7.5 ,  -7.25,  -7.  ,  -6.75,  -6.5 ,  -6.25,
        -6.  ,  -5.75,  -5.5 ,  -5.25,  -5.  ,  -4.75,  -4.5 ,  -4.25,
        -4.  ,  -3.75,  -3.5 ,  -3.25,  -3.  ,  -2.75,  -2.5 ,  -2.25,
        -2.  ,  -1.75,  -1.5 ,  -1.25,  -1.  ,  -0.75,  -0.5 ,  -0.25,
         0.  ,   0.25,   0.5 ,   0.75,   1.  ,   1.25,   1.5 ,   1.75,
         2.  ,   2.25,   2.5 ,   2.75,   3.  ,   3.25,   3.5 ,   3.75,
         4.  ,   4.25,   4.5 ,   4.75,   5.  ,   5.25,   5.5 ,   5.75,
         6.  ,   6.25,   6.5 ,   6.75,   7.  ,   7.25,   7.5 ,   7.75,
         8.  ,   8.25,   8.5 ,   8.75,   9.  ,   9.25,   9.5 ,   9.75,  10.  ])

In [4]:
times = numpy.arange(0,0.01+dt,dt)
nt = len(times)
print(nt)
times

51


array([ 0.    ,  0.0002,  0.0004,  0.0006,  0.0008,  0.001 ,  0.0012,
        0.0014,  0.0016,  0.0018,  0.002 ,  0.0022,  0.0024,  0.0026,
        0.0028,  0.003 ,  0.0032,  0.0034,  0.0036,  0.0038,  0.004 ,
        0.0042,  0.0044,  0.0046,  0.0048,  0.005 ,  0.0052,  0.0054,
        0.0056,  0.0058,  0.006 ,  0.0062,  0.0064,  0.0066,  0.0068,
        0.007 ,  0.0072,  0.0074,  0.0076,  0.0078,  0.008 ,  0.0082,
        0.0084,  0.0086,  0.0088,  0.009 ,  0.0092,  0.0094,  0.0096,
        0.0098,  0.01  ])

In [5]:
for t in range(1,nt):
    print(str(t) + "  " + str(times[t]))

1  0.0002
2  0.0004
3  0.0006
4  0.0008
5  0.001
6  0.0012
7  0.0014
8  0.0016
9  0.0018
10  0.002
11  0.0022
12  0.0024
13  0.0026
14  0.0028
15  0.003
16  0.0032
17  0.0034
18  0.0036
19  0.0038
20  0.004
21  0.0042
22  0.0044
23  0.0046
24  0.0048
25  0.005
26  0.0052
27  0.0054
28  0.0056
29  0.0058
30  0.006
31  0.0062
32  0.0064
33  0.0066
34  0.0068
35  0.007
36  0.0072
37  0.0074
38  0.0076
39  0.0078
40  0.008
41  0.0082
42  0.0084
43  0.0086
44  0.0088
45  0.009
46  0.0092
47  0.0094
48  0.0096
49  0.0098
50  0.01


In [6]:
initial_density_left = 1  # kg/m^3
initial_velocity_left = 0  # m/s
initial_pressure_left = 100  # kN/m^2

initial_pressure_left = 1000 * initial_pressure_left  # N/m^2

In [7]:
initial_density_right = 0.125  # kg/m^3
initial_velocity_right = 0  # m/s
initial_pressure_right = 10  # kN/m^2

initial_pressure_right = 1000 * initial_pressure_right  # N/m^2

In [8]:
density = initial_density_left
velocity = initial_velocity_left
pressure = initial_pressure_left

u1 = density
u2 = density * velocity
u3 = (pressure/(gamma-1)) + ((density * velocity**2)/2)

initial_u_left = numpy.array([u1, u2, u3])
initial_u_left

array([  1.00000000e+00,   0.00000000e+00,   2.50000000e+05])

In [9]:
density = initial_density_right
velocity = initial_velocity_right
pressure = initial_pressure_right

u1 = density
u2 = density * velocity
u3 = (pressure/(gamma-1)) + ((density * velocity**2)/2)

initial_u_right = numpy.array([u1, u2, u3])
initial_u_right

array([  1.25000000e-01,   0.00000000e+00,   2.50000000e+04])

In [10]:
left_indices, = numpy.where( x < 0 )
print(len(left_indices))
left_indices

40


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [11]:
right_indices, = numpy.where( x >= 0 )
print(len(right_indices))
right_indices

41


array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
       74, 75, 76, 77, 78, 79, 80])

In [12]:
initial_u = numpy.zeros((nx,3))

initial_u[left_indices] = initial_u_left
initial_u[right_indices] = initial_u_right

initial_u

array([[  1.00000000e+00,   0.00000000e+00,   2.50000000e+05],
       [  1.00000000e+00,   0.00000000e+00,   2.50000000e+05],
       [  1.00000000e+00,   0.00000000e+00,   2.50000000e+05],
       [  1.00000000e+00,   0.00000000e+00,   2.50000000e+05],
       [  1.00000000e+00,   0.00000000e+00,   2.50000000e+05],
       [  1.00000000e+00,   0.00000000e+00,   2.50000000e+05],
       [  1.00000000e+00,   0.00000000e+00,   2.50000000e+05],
       [  1.00000000e+00,   0.00000000e+00,   2.50000000e+05],
       [  1.00000000e+00,   0.00000000e+00,   2.50000000e+05],
       [  1.00000000e+00,   0.00000000e+00,   2.50000000e+05],
       [  1.00000000e+00,   0.00000000e+00,   2.50000000e+05],
       [  1.00000000e+00,   0.00000000e+00,   2.50000000e+05],
       [  1.00000000e+00,   0.00000000e+00,   2.50000000e+05],
       [  1.00000000e+00,   0.00000000e+00,   2.50000000e+05],
       [  1.00000000e+00,   0.00000000e+00,   2.50000000e+05],
       [  1.00000000e+00,   0.00000000e+00,   2.5000000

In [13]:
def compute_f(u, gamma):
    """Computes the flux vector f at each point x.
    
    Parameters
    ----------
    u : 2 dimensional array of floats
        array of the vector u at each point x
            --- vector u has 3 elements
            --- vector u contains the conserved euler variables
    
    gamma : float
            ratio of specific heats
    
    Returns
    -------
    f : 2 dimensional array of floats
        array of the vector f at each point x
            --- vector f has 3 elements
            --- vector f contains flux of the conserved euler variables
    """
    
    u1 = u[:,0]
    u2 = u[:,1]
    u3 = u[:,2]
    
    f1 = u2
    
    f2 = ((u2**2)/u1) + (gamma-1)*(u3 - (1/2)*((u2**2)/u1))
    
    f3 = (u3 + (gamma-1)*(u3 - (1/2)*((u2**2)/u1))) * (u2/u1)
    
    f = numpy.zeros_like(u)
    
    f[:,0] = f1
    f[:,1] = f2
    f[:,2] = f3
    
    return f

In [14]:
def richtmyer(u, nt, dt, dx, gamma):
    """Computes the solution with the Richtmyer scheme.
    
    Parameters
    ----------
    u : 2 dimensional array of floats
        array of the vector u at each point x
            --- vector u has 3 elements
            --- vector u contains the conserved euler variables
    nt : int
         Number of time steps
    dt : float
         Time-step size
    dx : float
         Mesh spacing
    gamma : float
            ratio of specific heats
    
    Returns
    -------
    u_n : 3 dimensional array of floats
          array of the vector u at each time t and at each point x
              --- vector u has 3 elements
              --- vector u contains the conserved euler variables
    """
    
    #initialize results array
    u_n = numpy.zeros((nt,len(u),3))
    #copy the initial u array into each 1st-dimension element of u_n
    u_n[:] = u.copy()
    
    for t in range(1,nt):
        
        u_star = u.copy()
        
        f = compute_f(u,gamma)
        
        u_star[:-1] = (1/2)*(u[1:] + u[:-1]) - (dt/(2*dx))*(f[1:] - f[:-1])
        
        f = compute_f(u_star,gamma)
        
        u[1:-1] = u[1:-1] - (dt/dx)*(f[1:-1] - f[:-2])
        
        u_n[t] = u.copy()
    
    return u_n

In [15]:
u_n = richtmyer(initial_u, nt, dt, dx, gamma)

In [16]:
final_u = u_n[-1]

final_u

array([[  1.00000000e+00,   0.00000000e+00,   2.50000000e+05],
       [  1.00000000e+00,   0.00000000e+00,   2.50000000e+05],
       [  1.00000000e+00,   0.00000000e+00,   2.50000000e+05],
       [  1.00000000e+00,   2.32830644e-14,   2.50000000e+05],
       [  1.00000000e+00,   5.93718141e-13,   2.50000000e+05],
       [  1.00000000e+00,   6.62403181e-12,   2.50000000e+05],
       [  1.00000000e+00,   6.57746568e-11,   2.50000000e+05],
       [  1.00000000e+00,   5.96523751e-10,   2.50000000e+05],
       [  1.00000000e+00,   4.94139967e-09,   2.50000000e+05],
       [  1.00000000e+00,   3.74458963e-08,   2.50000000e+05],
       [  9.99999999e-01,   2.59932445e-07,   2.50000000e+05],
       [  9.99999996e-01,   1.65429165e-06,   2.49999998e+05],
       [  9.99999974e-01,   9.65776166e-06,   2.49999991e+05],
       [  9.99999862e-01,   5.17246913e-05,   2.49999952e+05],
       [  9.99999321e-01,   2.54062501e-04,   2.49999762e+05],
       [  9.99996944e-01,   1.14360758e-03,   2.4999893

In [17]:
index, = numpy.where(x == 2.5)
index = index[0]
index

50

In [18]:
print(x[index])

2.5


In [19]:
u = final_u[index]

u1 = u[0]
u2 = u[1]
u3 = u[2]

u

array([  3.74691403e-01,   1.09639003e+02,   9.16680404e+04])

In [20]:
density = u1

print("At time t = 0.01 s and position x = 2.5 m, density = {:.2f} kg/m^3".format(density))

At time t = 0.01 s and position x = 2.5 m, density = 0.37 kg/m^3


In [21]:
velocity = u2/u1

print("At time t = 0.01 s and position x = 2.5 m, velocity = {:.2f} m/s".format(velocity))

At time t = 0.01 s and position x = 2.5 m, velocity = 292.61 m/s


In [22]:
pressure = (gamma - 1) * (u3 - (1/2)*((u2**2)/u1))

print("At time t = 0.01 s and position x = 2.5 m, pressure = {:.2f} N/m^2".format(pressure))

At time t = 0.01 s and position x = 2.5 m, pressure = 30250.89 N/m^2
